In [1]:
import torch
import numpy as np

# List

In [2]:
lst = [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [3]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Numpy Array

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.24054143, 0.87634344, 0.7833326 , 0.40666379],
       [0.43138736, 0.93077131, 0.21172595, 0.9822131 ],
       [0.48286861, 0.07574952, 0.99162657, 0.84572754]])

In [5]:
np1.dtype

dtype('float64')

# Tensors

## Definition

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d, tensor_2d.dtype

(tensor([[ 2.3851,  0.5358,  1.0856, -2.2370],
         [-0.1427, -1.2092, -0.3126,  1.1360],
         [ 1.0554, -1.4083, -1.1673,  0.6627]]),
 torch.float32)

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
tensor_np = torch.tensor(np1) # creazione tensore da numpy
tensor_np

tensor([[0.2405, 0.8763, 0.7833, 0.4067],
        [0.4314, 0.9308, 0.2117, 0.9822],
        [0.4829, 0.0757, 0.9916, 0.8457]], dtype=torch.float64)

## Operations

In [9]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reshape vs View

In [10]:
my_torch_shaped = my_torch.reshape(2,5)
my_torch_shaped

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
my_torch_viewed = my_torch.view(5,-1)
my_torch_viewed

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
my_torch[1] = 96
my_torch

tensor([ 0, 96,  2,  3,  4,  5,  6,  7,  8,  9])

In [13]:
my_torch_shaped

tensor([[ 0, 96,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [14]:
my_torch_viewed

tensor([[ 0, 96],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [15]:
my_torch2 = torch.tensor([[1,2,3],[4,5,6]])
my_torch_transposed = my_torch2.T
my_torch_transposed

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [16]:
my_torch_transposed.reshape(3,2)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [17]:
my_torch_transposed.view(3,2)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### Slice

In [18]:
my_torch[2:5]

tensor([2, 3, 4])

In [19]:
my_torch.reshape(5,2)[:,1:]

tensor([[96],
        [ 3],
        [ 5],
        [ 7],
        [ 9]])

### Math

In [20]:
tensor1 = torch.tensor([1,2,3,4,5])
tensor2 = torch.tensor([6,7,8,9,10])

In [21]:
# somma (somma di valori delle stesse posizione)
tensor1 + tensor2
torch.add(tensor1, tensor2)

tensor([ 7,  9, 11, 13, 15])

In [22]:
# sottrazione
tensor2 - tensor1
torch.sub(tensor2, tensor1)

tensor([5, 5, 5, 5, 5])

In [23]:
# prodotto
tensor1 * tensor2
torch.mul(tensor1, tensor2)

tensor([ 6, 14, 24, 36, 50])

In [24]:
# divisione
tensor2 / tensor1
torch.div(tensor2, tensor1)

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [25]:
# modulo
tensor2 % tensor1
torch.remainder(tensor2, tensor1)

tensor([0, 1, 2, 1, 0])

In [26]:
# esponeziale
tensor1 ** tensor2
torch.pow(tensor1, tensor2)

tensor([      1,     128,    6561,  262144, 9765625])

In [27]:
# Associare
#tensor1.add(tensor2)
#tensor1.sub(tensor2)
#tensor1.mul(tensor2)
tensor1.div(tensor2)
#tensor1.pow(tensor2)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])